### ISSUE TITLE
May I ask how can debug this project?

### ISSUE THREAD

**Issue by sdfhjytv** [Jimmy-7664/STD-MAE#5]
I have runned this project in terminal successfully.
But when I tried to run and debug the project run.py, it failed .
<img width="731" alt="屏幕截图 2024-04-17 151124" src="https://github.com/Jimmy-7664/STD_MAE/assets/152693205/9f9abac1-2f06-4e9d-adb1-d7466767114d">
Could you please tell me how I can debug this project?

**Comment by Jimmy-7664** [comment]
Great to hear that you successfully ran the project. 
Since STD-MAE is mainly built on Linux, when you run it on windows, you need to make sure that the relative imports don't cause problems especially running with pycharm. This maybe a issue but I think you can fix it by changing the relative import to an absolute import.
For debug:
1. STD-MAE provides a simple way to test each module. You can use torchsummary library to help you debug. Example can be refer to line 224 to 245 in [mask.py](https://github.com/Jimmy-7664/STD_MAE/blob/main/stdmae/stdmae_arch/mask/mask.py). In this case, you can write the summary and directly debug in pycharm.
2. Another simple and effective way is to print out the relevant information where you find it confusing.
3. You may consider using vscode to debug on Linux platform.

I hope this helps.

**Comment by czzhangheng** [comment]
I am having the same problem here. Usually I use PyCharm to run model, and write Run/Debug Configuration like this
<img width="825" alt="image" src="https://github.com/Jimmy-7664/STD-MAE/assets/67084806/d7d136d5-7a1c-43ad-9d84-ae989db7ea9f">
I checked "Working directory", it is right. But it still did not run. I am so confuse.
<img width="907" alt="image" src="https://github.com/Jimmy-7664/STD-MAE/assets/67084806/0529931e-d506-4857-9496-626be4b8e4ab">
However, I tried writing a "shell" configuration instead of "python". Then I ran it successfully.
<img width="828" alt="image" src="https://github.com/Jimmy-7664/STD-MAE/assets/67084806/fe96fc25-0ff7-4bb8-a34d-41bc131b8104">
<img width="1403" alt="image" src="https://github.com/Jimmy-7664/STD-MAE/assets/67084806/3e9a7e0b-a5fe-4337-869d-03a8d2c7e1b5">
Anyway, thanks for your work. It's easy to run. 🌹

**Comment by czzhangheng** [comment]
You may need to check your Run/Debug configurations. Set a right working directory instead of default. (refer my configuration)
![image](https://github.com/Jimmy-7664/STD-MAE/assets/67084806/83ee2b1b-0114-499f-9133-e1ae286b718e)
![image](https://github.com/Jimmy-7664/STD-MAE/assets/67084806/57c98a71-5b26-4c50-9a64-7b9d085d98aa)

Notice: Script parameter is `--cfg stdmae/TMAE_PEMS03.py --gpus '0'`
`--cfg 'stdmae/TMAE_PEMS03.py' --gpus '0'` is wrong!

Then, I only have one gpu, so I need to change configurations here.
![image](https://github.com/Jimmy-7664/STD-MAE/assets/67084806/84e7b51e-3508-4c68-8466-b57342b94639)
'CFG.GPU_NUM' is default to 1. I change it to 0.

Finally, you can run it or debug it successfully.
![image](https://github.com/Jimmy-7664/STD-MAE/assets/67084806/d0529015-20d6-4fe0-a9c0-735207716142)

**Comment by Jimmy-7664** [comment]
@czzhangheng Thank you for your kind help to this issue. :)

**Comment by sdfhjytv** [comment]
> You may need to check your Run/Debug configurations. Set a right working directory instead of default. (refer my configuration) ![image](https://private-user-images.githubusercontent.com/67084806/325846585-83ee2b1b-0114-499f-9133-e1ae286b718e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAyMTIsIm5iZiI6MTcxNDEwOTkxMiwicGF0aCI6Ii82NzA4NDgwNi8zMjU4NDY1ODUtODNlZTJiMWItMDExNC00OTlmLTkxMzMtZTFhZTI4NmI3MThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjE5OWI0N2I1NjMzNjc3ZTA5YzFmNjI4ZmQ2ZGU0OWEyODFkY2VjZTlhMjkxZjEzNmZkYjhkNzIwNzBlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bViDFeXKzdjAjLgcWqCeEei8wCkCqbqsHJWMWQl-zDk) ![image](https://private-user-images.githubusercontent.com/67084806/325857479-d818847d-620d-4561-95df-ae3e001d0636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAyMTIsIm5iZiI6MTcxNDEwOTkxMiwicGF0aCI6Ii82NzA4NDgwNi8zMjU4NTc0NzktZDgxODg0N2QtNjIwZC00NTYxLTk1ZGYtYWUzZTAwMWQwNjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTk2YTYyZmY3YTNjNjg2ZDJiZjViM2RmYTdlZDZkYjUyZGVhMTAzOWQ1YmVhZWQ0MzM0ZjllYmY4ZWYzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3oSI1ShlRMmoNb9H3eSoDrkpj6kynRO9QajsNtdDqY)
> 
> Notice: Script parameter is `--cfg stdmae/TMAE_PEMS03.py --gpus 0` `--cfg 'stdmae/TMAE_PEMS03.py' --gpus '0'` is wrong! ![image](https://private-user-images.githubusercontent.com/67084806/325856331-44a0c5d6-284f-4c72-a553-17fb50380653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAyMTIsIm5iZiI6MTcxNDEwOTkxMiwicGF0aCI6Ii82NzA4NDgwNi8zMjU4NTYzMzEtNDRhMGM1ZDYtMjg0Zi00YzcyLWE1NTMtMTdmYjUwMzgwNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMmQ4ZjRiNWQ5YjdkZTQyZTYxZDk3Y2NmYzllNTljZDFiMjJhZWNmOTNlOWViYzI0MmQ1NWM3NmY2NjJkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9VeHhPxid6DzncIIi6hY4Lwjtxlzh8sOXIzh4E390g)

Thank you so much, I can debug now!

**Comment by sdfhjytv** [comment]
> Great to hear that you successfully ran the project. Since STD-MAE is mainly built on Linux, when you run it on windows, you need to make sure that the relative imports don't cause problems especially running with pycharm. This maybe a issue but I think you can fix it by changing the relative import to an absolute import. For debug:
> 
>     1. STD-MAE provides a simple way to test each module. You can use torchsummary library to help you debug. Example can be refer to line 224 to 245 in [mask.py](https://github.com/Jimmy-7664/STD_MAE/blob/main/stdmae/stdmae_arch/mask/mask.py). In this case, you can write the summary and directly debug in pycharm.
> 
>     2. Another simple and effective way is to print out the relevant information where you find it confusing.
> 
>     3. You may consider using vscode to debug on Linux platform.
> 
> 
> I hope this helps.

Thank you for your help!
